# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763364c4dfd34e16674b78b75ceea07106afdb894b13f26d5d9daf2959997df4d80fba5a66667bb3b6c4069985fd83ac72470065e12512e95785642b3764352e

test:
  secret_key_base: 394a51a3ece2e563fb6f4b1f91cd834fcc8ce604c112436b4415f37cfc7f87b9ab72970fc26bf89cb338ab1ea968d30ab10b38e4f0bce221004c27c6fcb5cca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
